### ISSUE TITLE
WARNING: setcookie() expects parameter 3 to be integer ...

### ISSUE THREAD

**Issue by lck-git** [cmb69/poll_xh#15]
See [CMSimple_XH-Forum](https://cmsimpleforum.com/viewtopic.php?f=12&t=13109&p=68072#p68072) for Details.

**Comment by cmb69** [comment]
Indeed, there is an issue with ending dates larger than 2147483647 on 32bit PHP versions. Since the given timestamp is not verified and adjusted, after voting the respective cookie is not set.
